DROP TABLE IF EXISTS address CASCADE;
DROP TABLE IF EXISTS contact CASCADE;
DROP TABLE IF EXISTS person CASCADE;
DROP TABLE IF EXISTS deceased_person CASCADE;
DROP TABLE IF EXISTS person_address CASCADE;
DROP TABLE IF EXISTS person_contact CASCADE;
